### ISSUE TITLE
[feature]: Allow targeting specific app window

### ISSUE THREAD

**Issue by luser** [socsieng/sendkeys#57]
### What feature would you like to see in sendkeys?

I frequently have multiple Chrome windows open and would like to send a key press to a specific window. It would be nice if I could specify the window title to match so I could target a specific window.

**Comment by socsieng** [comment]
I think it's a good idea. I don't know if it could be done by window title, but might be able to do it with process id (`pid`).

Would that work for you?

What's the use case? Are you trying to automate a workflow unattended or is this something you would run every no and then; supervised?

**Comment by socsieng** [comment]
Are there any existing chrome extensions that would work for you?

A quick search returned this one: https://chrome.google.com/webstore/detail/easy-mute-for-google-meet/lgdalbjhcglejepghfomkmngebhaelga?hl=en
