### ISSUE TITLE
[bug]: Key combination sent with sendkeys usually have no effect on target application unless a dummy key is also sent

### ISSUE THREAD

**Issue by mahush** [socsieng/sendkeys#60]
### What went wrong?

When I sent the key combination `command`+`shift`+`m` to Microsoft Teams with the following command:

`sendkeys --application-name "Microsoft Teams" --characters "<k:m:shift,command>"`

Usually there is no effect (mute state in Microsoft Teams should have changed). Sometimes it works but I was not able to recognize a pattern. The interesting thing is there seems to be a workaround: adding additional keys, e.g.:

`sendkeys --application-name "Microsoft Teams" --characters "<k:m:shift,command> "` (no-op `space` at the end)
or
`sendkeys --application-name "Microsoft Teams" --characters "<c:shift><k:m:shift,command>"` (no-op `shift` at the beginning)

### Expected result:

I expect that there is no need for no-ops.

### Actual result:

Without no-ops there was no reliable delivery of the described keystrokes.

### Other information:

- Sendkeys version: v2.8.0
- Operating system: MacOS
- Processor (e.g. Intel, M1): M1
- There was a bug report in the past (https://github.com/socsieng/sendkeys/issues/56) where you @socsieng proposed to add a no-op to solve a very similar issue. I consider the need for such a no-op as bug. Maybe you agree ;-)

**Comment by alexreg** [comment]
I experience this too. The work-around I use is to pipe to stdin using `echo`, but this is clearly a major bug.

**Comment by alexreg** [comment]
I experience this too. Thanks for posting the work-around.

**Comment by socsieng** [comment]
> * There was a bug report in the past ([[bug]: I cannot refresh browser page #56](https://github.com/socsieng/sendkeys/issues/56)) where you @socsieng proposed to add a no-op to solve a very similar issue. I consider the need for such a no-op as bug. Maybe you agree ;-)

Yes, it's a bug, unfortunately I've got limited bandwidth to work on this. Will probably require a work-around until then.

**Comment by fharper** [comment]
Thanks @mahush, adding a space at the end of the command did it for me!
