### ISSUE TITLE
[feature]:  Auto repeat or loop a predefine action

### ISSUE THREAD

**Issue by inglesuniversal** [socsieng/sendkeys#61]
### What feature would you like to see in sendkeys?

Can this script have a feature to loop a predefine sendkeys command during a specified time?

Thanks

**Comment by socsieng** [comment]
I would prefer to keep this out of the tool. Have you considered using `cron` to schedule tasks instead.

https://chethansp.medium.com/schedule-job-with-crontab-on-macos-d47a1fda47e5
