### ISSUE TITLE
[bug]: Sendkeys to Windows RDP session: shift key not interpreted (?)

### ISSUE THREAD

**Issue by jknight** [socsieng/sendkeys#62]
### What went wrong?

```shell
> sendkeys --version
2.8.0

# It works locally ...
> echo "Hello_under_scores" | sendkeys -i 5
Hello_under_scores

# Now send to RDP App - not all chars come through:
> echo "Hello_under_scores" | sendkeys -i 5
```
![Screenshot-20221213-121220](https://user-images.githubusercontent.com/84268/207314851-08faeafd-5298-4b84-95e1-e091288618e7.jpg)

Also tried using a file as input - same result.

### Expected result:

Sending keys sends the correct characters.

### Actual result:

Sends correct chars locally but isn't working sending into RDP session.

### Theory:

All non [a-z] characters are `a` (?) It doesn't interpret the `shift` key correctly ?

### Previous Version

**This works on the previous node version.**

Same thing, swapped out to previous version:

![Screenshot-20221213-121243](https://user-images.githubusercontent.com/84268/207318681-6a3386b4-a7da-4fa6-a4cb-1857c63f5b02.jpg)

**Comment by socsieng** [comment]
ack: Thanks for the bug report, will look into it.

**Comment by socsieng** [comment]
I've made some changes to the way key press events are dispatched with version [`v3.0.1`](https://github.com/socsieng/sendkeys/releases/tag/v3.0.1) but don't currently have access to RDP. Are you able to confirm if this addresses the issue?

**Comment by WladyX** [comment]
I experience the same issue with VMware remote console app or remote console in browser, shift+letter=`a` letter for me.
This is on 3.0.2.

**Comment by socsieng** [comment]
I think I've got a fix out with `v4.0.0` if you can try again.

**Comment by WladyX** [comment]
I've tried 4.0.0 and:
1. still does not works, `Vlad` = `alad`, but apple scripts also have the same issue:
```
if application "Arc" is running then
	tell application "Arc" to activate
	delay 0.5
	tell application "System Events" to ¬
		tell application process "Arc"
			keystroke "Vlad"
		end tell
end if
```
there is small difference, applescript sends `vlad`, where your script sends `alad`, but still the applescript does not send the capital `V`
2. if the tab is not vmware console, but let's say google, both your sendkey and applescript send the corect `Vlad`
3. i think you forgot to increment the version inside the program?
```
❯ /opt/homebrew/bin/sendkeys --version
3.0.1
❯ ls -al /opt/homebrew/bin/sendkeys
lrwxr-xr-x  1 user  brew  37 Oct  7 08:44 /opt/homebrew/bin/sendkeys -> ../Cellar/sendkeys/4.0.0/bin/sendkeys
```
Thank you for your swift support @socsieng!
Really appreciate it!

**Comment by socsieng** [comment]
> 3. i think you forgot to increment the version inside the program?

Thanks for pointing this out. There was a problem with my CI/CD setup which meant that the latest version of the package wasn't published properly. It should now be fixed.

```
sendkeys --version
4.0.4
```

What this means is that the version you tested `4.0.0` was actually `3.0.1` which didn't have the fix applied. Do you mind testing again?

If that doesn't work, can I get you to try the following to help me narrow the problem down:

```
sendkeys --application-name "Arc" -d 0.6 --characters "<c:v:shift>lad"
```

**Comment by WladyX** [comment]
```
sendkeys --application-name "Arc" -d 0.6 --characters "Vlad"
```
```
sendkeys --application-name "Arc" -d 0.6 --characters "<c:v:shift>lad"
```
Both print now `vlad`, instead of previous `alad`, so small improvement there :)
But still no capital `V`.
For a google tab they both work as expected, just for the vmware console tab they misbehave.
Thank you for your effort & support!

**Comment by socsieng** [comment]
Thanks. Closing this issue for now.
