### ISSUE TITLE
[feature] Allow targeting window by PID

### ISSUE THREAD

**Issue by extr15** [socsieng/sendkeys#63]
Thanks for your work.
Sometimes I open multiple instances of one app, so I want to specify the window/process that receives the keys. It will be useful if you add a `--pid` option.
ps: https://github.com/socsieng/sendkeys/issues/57 is similar, but I think this is a common necessity.

**Comment by socsieng** [comment]
Thanks for the feedback. This feature should now be available from version [`2.9.1`](https://github.com/socsieng/sendkeys/releases/tag/v2.9.1).
