### ISSUE TITLE
[feature]: shortcut to terminate long running commands

### ISSUE THREAD

**Issue by vbabaria** [socsieng/sendkeys#79]
### What feature would you like to see in sendkeys?

it is indeed a great utility. we would love to have a shortcut command to abort long running command in the middle of execution in case if we have to manually intervene. thanks a lot for your contribution to open source community.

**Comment by socsieng** [comment]
This should now be available from version `4.1.1`:

To use <kbd>command</kbd> + <kbd>f12</kbd>, use the `--terminate-command "f12:command"`. Example:

```
sendkeys -a Notes -d 1 -c "long running sequence" \
  --terminate-command "f12:command"
```
